// Project Euler
// Problem 2 - Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

// Author:  David Khuu
// Date:    May 20, 2016

// Returns the num-th term of the Fibonacci sequence
function fibonacci(num) {
  if (num == 1) {
    return 1;
  } else if (num == 2) {
    return 2;
  } else {
    return fibonacci(num-1) + fibonacci(num-2);
  }
}
